FROM java:8 
EXPOSE 8080
ENV BDAPP=-Dspring.datasource.url=jdbc:postgresql://$IPBD:5432/integracao
ADD /target/integracaocontinua.jar integracaocontinua.jar
ENTRYPOINT ["java", "-jar", $BDAPP , "integracaocontinua.jar"]