FROM java:8 
RUN alternatives --install /usr/bin/javaws javaws /usr/java/latest/bin/javaws 200000
EXPOSE 8080
ADD /target/integracaocontinua.jar integracaocontinua.jar
ENTRYPOINT ["javaw", "-jar", "integracaocontinua.jar"]
