FROM java:8 
EXPOSE 8080
ADD /target/integracaocontinua.jar integracaocontinua.jar
ENTRYPOINT ["java", "-jar -Dspring.datasource.url=jdbc:postgresql://$IPBD:5432/integracao" , "integracaocontinua.jar"]